### ISSUE TITLE
Calendar Booking Form Bugs

### ISSUE THREAD

**Issue by ckeyes88** [HelpfulHuman/ExperiencesWidgets#78]
- "Go to next available" will go to a time slot that is sold out as the next available.
- Order details collection for both per order and per attendee is collecting information in the wrong spot or not at all.

https://share.getcloudapp.com/kpu71RNq

**Comment by maksimhn** [comment]
@ckeyes88

Question!
![image](https://user-images.githubusercontent.com/7401417/106097131-9a76f380-60eb-11eb-80e7-93e6cc2ab13a.png)

Top 2 are created via Embedded modal, bottom 2 - via Monthly widget (fixed, but not in PR yet). There is a difference in the way the widgets capture custom fields. Embedded widget only captures fields that are not “First Name”, “Last Name”, or “Email” as custom form data. Is that the preferred way? Currently Monthly widget stuffs everything to the custom fields value, but I can sync the behavior up with the Embedded

**Comment by ckeyes88** [comment]
@maksimhn 

Correct it should only store the custom details not the first/last/email which end up on the attendee fields. 

If I recall correctly, the server should put the fields where they’re supposed to be as long as the field names are correct. 

Did you check the api.ts file in embedded to see what that one does?

**Comment by maksimhn** [comment]
@ckeyes88 
That's the plan, I'll recreate embedded's behavior around custom fields. Just wanted to make sure that's what we want calendar widget to to as well. The PR should be up tonight if everything goes well 🤞

**Comment by maksimhn** [comment]
@ckeyes88 
PR https://github.com/HelpfulHuman/ExperiencesWidgets/pull/83

I also noticed a bug with `lineItems` quantity in orders where custom form fields need to be collected per order - it always books 1 spot instead of a number entered, will investigate tomorrow
